name: Build Android APK (Tablet Friendly)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Unzip project
        run: |
          unzip -q "*.zip" -d src
          echo "Listing after unzip:"
          ls -R src

      - name: Find Gradle project folder
        id: findproject
        run: |
          project_dir=$(find src -name "gradlew" -exec dirname {} \; | head -n 1)
          echo "Found project: $project_dir"
          echo "project_dir=$project_dir" >> $GITHUB_ENV

      - name: Build debug APK
        run: |
          cd $project_dir
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.project_dir }}/app/build/outputs/apk/debug/app-debug.apk
