name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Unzip project (any *.zip at repo root)
        run: unzip -q "*.zip" -d src

      - name: Locate project root (gradlew)
        id: locate
        run: |
          ROOT=$(find src -type f -name gradlew -printf '%h\n' | head -n 1)
          if [ -z "$ROOT" ]; then
            echo "gradlew not found under src/ — check your ZIP contents." >&2
            exit 1
          fi
          echo "Using project_dir=$ROOT"
          echo "project_dir=$ROOT" >> $GITHUB_ENV
          ls -la "$ROOT"

      - name: Add gradle.properties (enable AndroidX)
        run: |
          ROOT="$project_dir"
          echo "android.useAndroidX=true" >  "$ROOT/gradle.properties"
          echo "android.enableJetifier=true" >> "$ROOT/gradle.properties"
          echo "org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8" >> "$ROOT/gradle.properties"
          echo "Created $ROOT/gradle.properties:"
          cat "$ROOT/gradle.properties"

      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Build debug APK (verbose logs)
        run: |
          cd "$project_dir"
          chmod +x gradlew || true
          ./gradlew :app:assembleDebug --stacktrace --info | tee buildlog.txt

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.project_dir }}/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Gradle log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: ${{ env.project_dir }}/buildlog.txt

      - name: Show project structure (debug)
        if: always()
        run: |
          echo "Top-level files under project_dir:"
          find "$project_dir" -maxdepth 2 -type f | sort
