name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Unzip project
        run: unzip -q "*.zip" -d src

      - name: Detect project dir
        id: detect
        run: |
          PROJECT_DIR=$(find src -maxdepth 4 -type f -name "settings.gradle*" -printf '%h\n' | head -n 1)
          echo "project_dir=$PROJECT_DIR" >> $GITHUB_ENV

      - name: Add gradle.properties
        run: |
          echo "android.useAndroidX=true" >> "$project_dir/gradle.properties"
          echo "android.enableJetifier=true" >> "$project_dir/gradle.properties"
          echo "org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8" >> "$project_dir/gradle.properties"
          cat "$project_dir/gradle.properties"

      - name: Build debug APK
        run: |
          cd "$project_dir"
          chmod +x gradlew || true
          ./gradlew :app:assembleDebug --stacktrace --info | tee buildlog.txt

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ${{ env.project_dir }}/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Gradle log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-log
          path: ${{ env.project_dir }}/buildlog.txt
